version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=root
    depends_on:
      - db
    networks:
      - laravel
    volumes:
      - storage_data:/var/www/storage/app/public/projects  # Pastikan nginx juga bisa membaca storage

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: laravel_nginx
    restart: always
    ports:
      - "5000:80"
    depends_on:
      - app
    networks:
      - laravel
    volumes:
      - storage_data:/var/www/public/storage/projects  # Pastikan nginx juga bisa membaca storage

  db:
    image: mysql:latest
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  laravel:

volumes:
  mysql_data:
  storage_data:  # Definisikan volume untuk storage
